version: '3.4'

services:
  automation:
    image: test305/automation:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      NODE_ENV: production
    ports:
      - "3000"
    deploy:
      replicas: 3

# version: '3'

# services:
#   automation:
#     image: automation
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - NODE_ENV=production
#     command: ["npx", "playwright", "test"]
#     ports:
#       - "3001"

#   automation-2:
#     image: automation
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - NODE_ENV=production
#     command: ["npx", "playwright", "test"]
#     ports:
#       - "3002"